accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('', views.indexView, name='home'),
    path('login/', LoginView.as_view(template_name='login.html', redirect_field_name='homepage:index'), name = 'login_url'), 
    path('register/', views.register, name = 'register_url'),
    path('logout/', LogoutView.as_view(next_page='homepage:index'), name = 'logout'),
]

books/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'books'

urlpatterns = [
    path('', views.index, name='home'),
    path('data/', views.data, name='data'),
]

sarangkarir/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('article/', include('article.urls',namespace='article')),
    path('contact/', include('contact.urls', namespace = 'contact')),
    path('event/', include('event.urls', namespace ='event')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('books/', include('books.urls', namespace='books')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def indexView(request): 
    return render(request, 'index1.html')

# @login_required
def dashboardView(request):

    return render(request, 'dashboard.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login_url')
    else:
        form = UserCreationForm()

    return render(request, 'register.html', {'form':form})

def registerView(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login_url')
    else:
        form = UserCreationForm()

    return render(request, 'registration/register.html', {'form':form})

accounts/templates/dashboard.html
{% extends 'index1.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card p-5 text-center">
        <h1>Welcome to Your Dashboard, <span class="text-warning ">{{ user.username }}</span></h1>
        <a href="{% url 'accounts:home' %}" class="btn-outline-dark btn mt-5">Home</a>
    </div>
</div>
{% endblock %}

accounts/templates/index1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SarangKarir</title>
    <link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:300,400,500,600|Poppins:400,600|Roboto:100,300,400,500,700,900|Monoton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/ico" href="{% static 'images/sarangkarir Logo.png' %}">
</head>
<body>
    
    {% block content %}
    <div class="container mt-5">
        <div class="card text-center p-5">
            <h1>Welcome to the Home Page</h1>

            {% if user.is_authenticated %}
                <a href="{% url 'accounts:dashboard' %}" class="btn-outline-dark btn mt-5">
                    Your Dashboard
                </a>
                <a href="{% url 'accounts:logout' %}" class="btn-outline-dark btn mt-2">
                    Logout
                </a>
            {% else %}
                <a href="{% url 'accounts:login_url' %}" class="btn-outline-dark btn mt-5">
                    Login
                </a>
                <a href="{% url 'accounts:register_url' %}" class="btn-outline-dark btn mt-2">
                    Register
                </a>
            {% endif %}
        </div>
    </div>
    {% endblock %}
</body>
</html>

accounts/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SarangKarir</title>
    <link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:300,400,500,600|Poppins:400,600|Roboto:100,300,400,500,700,900|Monoton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/ico" href="{% static 'images/sarangkarir Logo.png' %}">
</head>
<body>
    {% block content %}
    <div class="p-3">
            <a href="{% url 'homepage:index' %}">
                <img src="{% static 'images/LogoBlack.png' %}" alt="logo" style="width: 40px; height: 55px;" class="logoimg">
            </a>
            <div class="float-right">
                <a href="{% url 'homepage:index' %}"">
                    <button type="button" class="btn btn-outline-dark btn-lg btn-find">Home</button>
                </a>
            </div>
        </div>
    <div class="container mt-3">
            <div class="text-center card p-5">
                <h1>User Login</h1>
                <form method="POST" class="mt-2">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn-outline-dark btn">Login</button>
                </form>
                <p class="mt-3">Don't have an account yet? register <a href="{% url 'accounts:register_url' %}">here</a></p>
            </div>
        </div>
    {% endblock %}
</body>
</html>

accounts/templates/register.html
 {% extends 'index1.html' %}
{% load static %}
 {% block content %}
 <div class="p-3">
        <a href="{% url 'homepage:index' %}">
            <img src="{% static 'images/LogoBlack.png' %}" alt="logo" style="width: 40px; height: 55px;" class="logoimg">
        </a>
        <div class="float-right">
            <a href="{% url 'homepage:index' %}"">
                <button type="button" class="btn btn-outline-dark btn-lg btn-find">Home</button>
            </a>
        </div>
    </div>
 <div class="container mt-3">
    <div class="card p-5">
        <h1>Create New Account</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-outline-dark">Register</button>
        </form>
    </div>
</div>
 {% endblock %}