accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('', views.indexView, name='home'),
    path('login/', LoginView.as_view(template_name='login.html', redirect_field_name='homepage:index'), name = 'login_url'), 
    path('register/', views.register, name = 'register_url'),
    path('logout/', LogoutView.as_view(next_page='homepage:index'), name = 'logout'),
]

article/urls.py
from django.conf.urls import url
from django.urls import path
from .views import articles, articles_create

app_name = 'articles'

urlpatterns = [
    
    path('articles/', articles, name='articles'),
    path('articles_create/', articles_create, name='article2')
]

books/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'books'

urlpatterns = [
    path('', views.index, name='home'),
    path('data/', views.data, name='data'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('',views.contact, name='contact'),
    path('getAjax/',views.getAjax, name='getAjax'),

]

event/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'event'

urlpatterns = [
    path('', event, name='event'),
    path('sched_add/', sched_add, name='sched_add'),
    path('sched_edit/<int:pk>', sched_edit, name='sched_edit'),
    path('sched_delete/<int:pk>', sched_delete, name='sched_delete'),
    path('getbook/<book_name>', readJSON, name='json'),
]

sarangkarir/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('article/', include('article.urls',namespace='article')),
    path('contact/', include('contact.urls', namespace = 'contact')),
    path('event/', include('event.urls', namespace ='event')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('books/', include('books.urls', namespace='books')),
]

templates/components/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>SarangKarir</title>
<link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:300,400,500,600|Poppins:400,600|Roboto:100,300,400,500,700,900|Monoton&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="icon" type="image/ico" href="{% static 'images/sarangkarir Logo.png' %}">

templates/components/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'homepage:index' %}">
        <img src="{% static 'images/sarangkarir Logo.png' %}" alt="scratch" style="width:40px; height: 55px;">
    </a>
    <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:index' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:preference' %}">Find</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'article:articles' %}">Article</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'event:event' %}">Jobfair</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'books:home' %}">Books</a>
            </li>
        </ul>
        <ul class="navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                    <h3 style="color: white;">Hello, {{ user.username }}</h3>
            </li>
            {% endif %}
            <li>
                {% if user.is_authenticated %}
                <a href="{% url 'accounts:logout' %}">
                    <button type="button" class="btn btn-outline-light btn-sign">Sign Out</button>
                </a>
                {% else %}
                <a href="{% url 'accounts:login_url' %}">
                    <button type="button" class="btn btn-outline-light btn-sign">Sign In</button>
                </a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>