books/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'books'

urlpatterns = [
    path('', views.index, name='home'),
    path('data/', views.data, name='data'),
]

homepage/urls.py
from django.urls import path
from .views import index, preference

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
    path('preference/', preference, name='preference'),
]

sarangkarir/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('article/', include('article.urls',namespace='article')),
    path('contact/', include('contact.urls', namespace = 'contact')),
    path('event/', include('event.urls', namespace ='event')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('books/', include('books.urls', namespace='books')),
]

homepage/models.py
from django.db import models

# Create your models here.
INDUSTRY_CHOICES = (
    (1,"Technology"),
    (2,"Healthcare"),
)

BACKGROUND_CHOICES = (
    (1,"University"),
    (2,"High School"),
)

SKILL_CHOICES = (
    (1,"Managing"),
    (2,"Working"),
)

WAGE_CHOICES = (
    (1,"Rp 1mi - Rp 15mi"),
    (2,"Rp 15mi - Rp 30mi"),
)   

class Job(models.Model):
    name = models.CharField(max_length = 100, default='Nama')
    description = models.CharField(max_length = 500, default = 'Deskripsi')
    foto = models.CharField(max_length = 500, default = 'url foto')
    industry = models.IntegerField(default=1, choices=INDUSTRY_CHOICES)
    background = models.IntegerField(default=1, choices=BACKGROUND_CHOICES)
    skill = models.IntegerField(default=1, choices=SKILL_CHOICES)
    wage = models.IntegerField(default=1, choices=WAGE_CHOICES)

    def __str__(self):
        return self.name + " - " + self.getIndustry() + " - " + self.getBackground() + " - " + self.getSkill() + " - " + self.getWage()

    def getIndustry(self):
        if self.industry == 1:
            return "Technology"
        elif self.industry == 2:
            return "Healthcare"
    
    def getBackground(self):
        if self.background == 1:
            return "University"
        elif self.background == 2:
            return "High School"

    def getSkill(self):
        if self.skill == 1:
            return "Managing"
        elif self.skill == 2:
            return "Working"

    def getWage(self):
        if self.wage == 1:
            return "Rp 1mi - Rp 15mi"
        elif self.wage == 2:
            return "Rp 15mi - Rp 30mi"

class User(models.Model):
    name = models.CharField(max_length = 100, default='Nama')

    def __str__(self):
        return self.name

homepage/forms.py
from django import forms

INDUSTRY_CHOICES = (
    (1,"Technology"),
    (2,"Healthcare"),
)

BACKGROUND_CHOICES = (
    (1,"University"),
    (2,"High School"),
)

SKILL_CHOICES = (
    (1,"Managing"),
    (2,"Working"),
)

WAGE_CHOICES = (
    (1,"Rp 1mi - Rp 15mi"),
    (2,"Rp 15mi - Rp 30mi"),
)

class EduForm(forms.Form):
    name = forms.CharField(max_length=100, label="Your Name", required=True)
    name.widget.attrs['class'] = 'form-control'
    name.widget.attrs['style'] = 'width: 50vh;'

    industry = forms.ChoiceField(choices = INDUSTRY_CHOICES, label="Choose an Industry", initial='', required=True,
    )
    industry.widget.attrs['class'] = 'form-control'
    industry.widget.attrs['style'] = 'width:50vh;'
    
    background = forms.ChoiceField(choices = BACKGROUND_CHOICES, label="Educational Background", initial='', required=True,
    )
    background.widget.attrs['class'] = 'form-control'
    background.widget.attrs['style'] = 'width:50vh;'

    skill = forms.ChoiceField(choices = SKILL_CHOICES, label="Choose Your Skill", initial='', required=True,
    )
    skill.widget.attrs['class'] = 'form-control'
    skill.widget.attrs['style'] = 'width:50vh;'

    wage = forms.ChoiceField(choices = WAGE_CHOICES, label="Desired Wage", initial='', required=True,
    )
    wage.widget.attrs['class'] = 'form-control'
    wage.widget.attrs['style'] = 'width:50vh;'

    # def __init__(self, *args, **kwargs):
    #     super(EduForm, self).__init__(*args, **kwargs)
    #     self.fields['status'].widget.attrs['class'] = 'form-control'
    # class Meta:
    #     model = Jadwal
    #     fields = [
    #         'nama_kegiatan',
    #         'kategori',
    #         'tempat',
    #         'tanggal',
    #         'waktu',
    #     ]

homepage/views.py
from django.shortcuts import render
from .forms import EduForm
from .models import *
# Create your views here.
def index(request):
    return render(request, 'index.html')

def preference(request):
    if request.method == 'POST':
        form = request.POST
        # print(form['background'])

        result = Job.objects.filter(industry = form['industry'], background = form['background'], skill=form['skill'], wage=form['wage']).values()
        user = User.objects.create(name=form['name'])
        
        response = {
            'result':result,
            'user':user,
        }
        return render(request, "jobres.html", response)
        
    else :
        form = EduForm()
        return render(request, 'preference.html', {'form' : form})




    

homepage/templates/index.html
{% extends 'sarangkarir/base.html' %}
{% load static %}

{% block body %}
    <div class = "landing bg text-center">
        <p>Find Your Next Job With SarangKarir Right Now</p>
        <a href="{% url 'homepage:preference' %}">
            <button type="button" class="btn btn-outline-light btn-lg">Find Now</button>
        </a>
    </div>
    <div class="findyournext">
        <div class = "container">
            <div class="row">
                <div class="col-6 text-center p-2">
                    <img src="{% static 'images/anagram.png' %}" alt="find your nex job" style="width:40vw; padding-bottom: 48px;" class="text-center" id="anagram">
                    <a href="{% url 'homepage:preference' %}">
                        <button type="button" class="btn btn-outline-dark btn-lg btn-find">Find Now</button>
                    </a>
                </div>
                <div class="col-6 p-2">
                    <h2>Find your next job with Sarang Karir</h2>
                    <p>SarangKarir is a company that tries to help fulfill your need of job. Through this website, we offer you some of the jobs you might find interesting as the list of jobs displayed is based on your own job interest. Get your function and be a better you with us! </p>
                </div>
            </div>
        </div>
    </div> 
    <div class="FAQ">
        <div class="container bg-light p-5 bulet shadow container-FAQ">
            <div>
                <img src="{% static 'images/FAQ.png' %}" alt="FAQ" style="width: 70vw;">
            </div>
            <div class="row">
                <div class="col-6">
                    <h3>1. How to find job matches in Sarang Karir?</h3>
                </div>
                <div class="col-6">
                    <p>Answer a few simple questions about your job preference. The SarangKarir Job Finder will search for jobs that match your criteria. Choose desired job and apply by dropping your CV here!</p>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <h3>2. What are the features provided by Sarang Karir?</h3>
                </div>
                <div class="col-6">
                    <p>There are some features that might help you easily get the informations that you need. They are the sign-in and sign-up requirements, job-related articles, forms of needed educational background, industry, skill, and wage, some jobs displayed after filtering by the previous forms, social medias, and feedback form.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <h3>3. Whom should I contact if I’m interested to one particular job?</h3>
                </div>
                <div class="col-6">
                    <p>You can contact the ones who become the contact person for each job recommendation displayed. We have made sure that these contacts are easy to reach and responsive.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <h3>4. What differs Sarang Karir if compared to other companies? </h3>
                </div>
                <div class="col-6">
                    <p>The way we sort the information based on your interest is what makes us different from other companies. We give you ONLY the job recommendations and articles that you would later find interesting.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <h3>5. How does Sarang Karir do research for its data?</h3>
                </div>
                <div class="col-6">
                    <p>For our information data, we are doing a research and result from any IT or economy study done for Indonesia’s technology and economy growth recent condition. Thus, we can ensure that our data are valid.</p>
                </div>
            </div>
        </div>
    </div> 
    <!-- <div class="contain explore" id="explorejob">
        <h1 class="text_explore">EXPLORE THE JOBS</h1>

        <div class="row text-center text-lg-left">

            <div class="col-lg-3 col-md-6 col-6">
                <a href="{% static 'images/businessman.jpg' %}" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail" src="{% static 'images/businessman.jpg' %}" alt="">
                </a>
            </div>
            <div class="col-lg-3 col-md-6 col-6">
                <a href="{% static 'images/doctor.jpg' %}" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail" src="{% static 'images/doctor.jpg' %}" alt="">
                </a>
            </div>
            <div class="col-lg-3 col-md-6 col-6">
                <a href="{% static 'images/engineer.jpg' %}" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail" src="{% static 'images/engineer.jpg' %}" alt="">
                </a>
            </div>
            <div class="col-lg-3 col-md-6 col-6">
                <a href="{% static 'images/gardener.jpg' %}" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail" src="{% static 'images/gardener.jpg' %}" alt="">
                </a>
            </div>
            <div class="col-lg-3 col-md-6 col-6">
                <a href="{% static 'images/meeting.jpg' %}" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail" src="{% static 'images/meeting.jpg' %}" alt="">
                </a>
            </div>
            <div class="col-lg-3 col-md-6 col-6">
                <a href="{% static 'images/programmer.jpg' %}" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail" src="{% static 'images/programmer.jpg' %}" alt="">
                </a>
            </div>
            <div class="col-lg-3 col-md-6 col-6">
                <a href="{% static 'images/publicspeaker.jpg' %}" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail" src="{% static 'images/publicspeaker.jpg' %}" alt="">
                </a>
            </div>
            <div class="col-lg-3 col-md-6 col-6">
                <a href="{% static 'images/teacher.jpg' %}" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail" src="{% static 'images/teacher.jpg' %}" alt="">
                </a>
            </div>
        </div>
    </div> -->
    <div class="explorejobs">
        <div class="container pb-5">
            <h1 class="text_explore">EXPLORE THE JOBS</h1>
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                    <img class="d-block w-100" src="{% static 'images/teacher.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'images/publicspeaker.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'images/businessman.jpg' %}" alt="Third slide">
                    </div>
                    <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'images/founder-startup.jpg' %}" alt="Third slide">
                    </div>
                    <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'images/head-it.jpg' %}" alt="Third slide">
                    </div>
                    <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'images/meeting.jpg' %}" alt="Third slide">
                    </div>
                    <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'images/software-engineer.jpg' %}" alt="Third slide">
                    </div>
                    <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'images/webdev.jpeg' %}" alt="Third slide">
                    </div>

                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <div class="text-center switch change justify-content-center pb-5 explorejobs">Dark mode:              
        <span class="inner-switch2">OFF</span>
    </div>
    
    
{% endblock body %}

homepage/templates/jobres.html
{% extends 'sarangkarir/findjob.html' %}
{% load static %}

{% block body%}
<div class="jobresult pb-3">
    <div class="p-3">
        <a href="{% url 'homepage:index' %}">
            <img src="{% static 'images/LogoBlack.png' %}" alt="logo" style="width: 40px; height: 55px;" class="logoimg">
        </a>
        <div class="float-right">
            <a href="{% url 'homepage:index' %}"">
                <button type="button" class="btn btn-outline-dark btn-lg btn-find">Home</button>
            </a>
        </div>
    </div>
    <div class="text-center mb-3">
        <h2>Hello {{ user.name }}, this is the job for you :</h2>
    </div>
    <div class="container mt-2 pr-5 pl-5 text-center d-flex justify-content-center">
        {% for i in result %}
        <div class="card" style="width: 50vw;">
            <img src="{{ i.foto }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h3 class="card-text">{{ i.name }}</h3>
                <p class="card-text">{{ i.description }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="switch text-center mb-5">Dark mode:              
    <span class="inner-switch">OFF</span>
</div>


{% endblock body %}

homepage/templates/preference.html
{% extends 'sarangkarir/findjob.html' %}
{% load static %}

{% block body%}
<div class="p-3">
    <a href="{% url 'homepage:index' %}">
        <img src="{% static 'images/LogoBlack.png' %}" alt="logo" style="width: 40px; height: 55px;" class="logoimg">
    </a>
</div>
<div class="choices">
    <h1 class="text-center">CHOOSE YOUR PREFERENCES</h1>
    <!-- something -->
    <div class="d-flex justify-content-center">
        <form action="{% url 'homepage:preference' %}" method="POST" > {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center mt-4">
                <button type="submit" class="btn btn-outline-dark btn-lg btn-find">FIND</button>
            </div>
        </form>
    </div>
</div>
<div class="switch text-center mt-3">Dark mode:              
    <span class="inner-switch">OFF</span>
</div>

{% endblock body %}